service: java-lambda-example

provider:
  name: aws
  runtime: java8
  region: eu-west-1
  tracing: true

  iamRoleStatements:
    - Effect: Allow
      Action:
        - xray:PutTraceSegments
        - xray:PutTelemetryRecords
      Resource: "*"

package:
  artifact: build/libs/java-example-uber.jar


plugins:
  - serverless-plugin-tracing


functions:
  hello:
    handler: fr.xebia.HandlerHTTP
    events:
      - http:
          path: hello
          method: get
