service: java-lambda-example

provider:
  name: aws
  runtime: java8
  stage: dev
  region: eu-west-1

package:
  artifact: build/libs/java-example-uber.jar

functions:
  hello:
    handler: fr.xebia.HandlerHTTP
    events:
      - http:
          path: hello
          method: get
