service: nodejs-lambda-example

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 1024
  region: eu-west-1
  tracing: true

  iamRoleStatements:
    - Effect: Allow
      Action:
        - xray:PutTraceSegments
        - xray:PutTelemetryRecords
      Resource: "*"

plugins:
  - serverless-plugin-tracing

functions:
  hello:
    handler: lambda.handler
    events:
      - http:
          path: hello
          method: get
